### ISSUE TITLE
Source to be attributed

### ISSUE THREAD

**Issue by kingroryg** [t3nsor/SPOJ#2]
Hi , I have made a website which would serve as a solution archive for all problems on the internet .  i would like to use solutions from this repo . each source file would be attributed to you and redirected to any link you prefer .
Can I have your permission to use the source from this repo ? thanks !

**Comment by t3nsor** [comment]
All code in this repository has been released into the public domain unless noted otherwise.
Feel free to attribute it to me and link to this repo.
