### ISSUE TITLE
WRONG OUTPUT

### ISSUE THREAD

**Issue by victansh** [t3nsor/SPOJ#8]
YOUR CODE OUTPUT SEEMS INCORRECT CHECK
FOR THIS TEST CASE
20
1 2 3 298 398395 3434004  34304 23242 58045 3422 23243545 445443 323232454 242424 343543 2232434 3533545342 232323 43253 565
5
0 2 8 23
0 10 18 34343
1 9 23444323
1 15 43535
0 2 16 13232

**Comment by t3nsor** [comment]
Uh, what problem is this for?
